// 003-auth-authorization (T015, Art 8 [NN], research R9). Reads the static OpenAPI document
// `apps/api/scripts/export-openapi.ts` writes to `docs/openapi.json` and generates
// `src/index.ts` from it via `openapi-typescript`'s programmatic API — no live server required,
// so this runs the same way locally and in CI. Nothing under `src/index.ts` is ever hand-written;
// this script is the only thing that touches it. `src/content/` is a deliberate, permanent
// exception — hand-written content DTOs with their own package export (research R6,
// 004-web-design-system-port) — this script does not generate and must never overwrite it.
import { readFile, writeFile } from "node:fs/promises";
import path from "node:path";
import openapiTS, { astToString } from "openapi-typescript";

const specPath = path.resolve(import.meta.dirname, "../../../docs/openapi.json");
const outPath = path.resolve(import.meta.dirname, "../src/index.ts");

// Passed as an already-parsed object, not a path/URL string — openapi-typescript's path/URL
// input mode goes through a schema-format validator that expects a `$ref`-resolvable document
// shape (redoc-style) and rejects a plain locally-written OpenAPI JSON file; passing the parsed
// object skips that resolution step entirely, which this single-file, no-$ref document never
// needed anyway.
const document = JSON.parse(await readFile(specPath, "utf-8"));
const ast = await openapiTS(document);
const header =
  "// GENERATED by packages/types/scripts/generate.ts from docs/openapi.json — Article 8 [NN].\n" +
  "// Do not hand-edit. Run `pnpm --filter @pascca/types generate` after the API's routes change.\n\n";

await writeFile(outPath, header + astToString(ast), "utf-8");

console.log(`Types generated at ${outPath}`);
